### PR TITLE
Issue10 lti configuration

### PR DESCRIPTION
**Pull request by bryanlandia**
Makes LTI spec namespace configurable.  Also see commit  to ISC configuration birch branch https://github.com/ISCLC/ISC/commit/99b5b5d65719de7b514fac596a798b84a5c5b19d
That commit adds JSON to server_vars.yml that sets the customized LTI namespace url ISC will use.

### CODE REVIEW

**Comment by cewing** [comment]
In addition to adding the setting to `cms/envs/aws.py`, `cms/envs/common.py`, `lms/envs/aws.py`, and `lms/envs/common.py`, we will probably need to add it to `tests.py` in both places.  I'm not entirely clear on the relationship, but so far every time I've touched a settings file, I've had to add to the tests one too.

**Comment by cewing** [comment]
Actually, @bryanlandia, I had imagined this as a setting on the xmodule itself, so that one could provide different a different LTI namespace for different LTI providers.  The setting could be quite useful for establishing a global default, but I was thinking that being able to override it per-unit would also be useful.

@natea can you speak to this?  I don't want @bryanlandia to do work that isn't required, but I felt that having a per-block setting would be useful, and would improve the chances of a PR to core EdX being accepted.

**Comment by bryanlandia** [comment]
Thanks @cewing Looks like cms.env.aws.py, cms.env.test.py, lms.env.aws.py and lms.env.test.py  `import * from .common` so I didn't include the new setting there.   Or is it practice to provide the setting key in the aws and test files, as well to make it easier to override?

As far as making it a setting on the xmodule, I wasn't aware of that approach, but if that's something Nate wants to do I'll do that.

**Comment by cewing** [comment]
Cool, @bryanlandia, let's see what @natea says

**Comment by natea** [comment]
I don't know enough about LTI to have an opinion on this but I think we should ask @nedbat and @cpennington if they think the approach taken here is appropriate.

**Pull request merged**
